// Copyright 2016-2017 FutureQuest, Inc.

// Code generated by go generate; DO NOT EDIT.
// This file was generated by genVersion at
// 2017-10-10 15:39:50.33477222 -0700 PDT m=+0.000154503

package FQversion

import (
	"futurequest.net/FQgolibs/FQversion"
)

var (
	PROG    string = "FQgolibs"
	VERSION string = "v6.4.0"
	BUILD   string = "20171010@15:39:50"
)

func init() {
	FQversion.Register(PROG, VERSION, BUILD)
}

func (*Version) Version() string {
	return FQversion.ProgVersion(PROG, VERSION, BUILD)
}
